version: "3.7"

services:
  vote:
    image: votingappimages.azurecr.io/vote-im
    build:
    context: .
      dockerfile: vote/Dockerfile
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:5.0-alpine3.10
    ports: ["6379"]

  worker:
    image: votingappimages.azurecr.io/worker-im
    build:
    context: .
      dockerfile: worker/Dockerfile

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data

  result:
    image: votingappimages.azurecr.io/result-im
    build:
    context: .
      dockerfile: result/Dockerfile
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
volumes:
  db-data:
